//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("https://push.flccis.com", ClrNamespace="push.flccis.com")]

namespace Exchange.Contracts.ShowCase.CCIS
{
    using Exchange.Contracts.Services;
    using System.Runtime.Serialization;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ccisFile", Namespace = "https://push.flccis.com")]
    public enum ccisFile : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ccisparty = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        cciscase = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ccischarge = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ccisfiling = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ccisattorney = 4,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class submitData
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "submitData", Namespace = "https://push.flccis.com", Order = 0)]
        public submitDataBody Body;

        public submitData()
        {
        }

        public submitData(submitDataBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class submitDataBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string ucn;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public Exchange.Contracts.ShowCase.CCIS.ccisFile ccisFile;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string xml;

        public submitDataBody()
        {
        }

        public submitDataBody(string ucn, Exchange.Contracts.ShowCase.CCIS.ccisFile ccisFile, string xml)
        {
            this.ucn = ucn;
            this.ccisFile = ccisFile;
            this.xml = xml;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class submitDataResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "submitDataResponse", Namespace = "https://push.flccis.com", Order = 0)]
        public submitDataResponseBody Body;

        public submitDataResponse()
        {
        }

        public submitDataResponse(submitDataResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "")]
    public partial class submitDataResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string key;

        public submitDataResponseBody()
        {
        }

        public submitDataResponseBody(string key)
        {
            this.key = key;
        }
    }
}